#![allow(clippy::pedantic, clippy::nursery)] // Dense TA kernels: short names / similar locals; core Clippy groups still `-D` in CI.

pub mod ad_line;
pub mod adx;
pub mod aggregate_one_hour;
pub mod alma;
pub mod aroon;
pub mod atr;
pub mod awesome_oscillator;
pub mod bollinger;
pub mod bollinger_bandwidth;
pub mod bollinger_pct_b;
pub mod candlestick_patterns;
pub mod cci;
pub mod chaikin_oscillator;
pub mod chandelier_exit;
pub mod cmf;
pub mod cmo;
pub mod dema;
pub mod donchian;
pub mod elder_ray;
pub mod ema;
pub mod force_index;
pub mod hist_vol;
pub mod hull_ma;
pub mod ichimoku;
pub mod kama;
pub mod keltner;
pub mod kst;
pub mod kvo;
pub mod linear_regression;
pub mod macd;
pub mod mama_fama;
pub mod mass_index;
pub mod mcginley;
pub mod mfi;
pub mod nvi_pvi;
pub mod obv;
pub mod parabolic_sar;
pub mod pivot_classic;
pub mod pivot_fib;
pub mod ppo;
pub mod pvo;
pub mod roc;
pub mod rolling_median;
pub mod rsi;
pub mod sma;
pub mod stoch_rsi;
pub mod stochastic;
pub mod supertrend;
pub mod tema;
pub mod trix;
pub mod tsi;
pub mod ttm_squeeze;
pub mod ultosc;
pub mod vidya;
pub mod volume_ema;
pub mod volume_profile;
pub mod volume_sma;
pub mod vortex;
pub mod vwap;
pub mod vwma;
pub mod williams_r;
pub mod wma;
pub mod zscore;

pub use ad_line::ad_line_series;
pub use adx::adx_series;
pub use aggregate_one_hour::aggregate_to_higher_tf;
pub use alma::alma_series;
pub use aroon::aroon_series;
pub use atr::atr_series;
pub use awesome_oscillator::awesome_oscillator_series;
pub use bollinger::{BollingerBar, bollinger_series};
pub use bollinger_bandwidth::bollinger_bandwidth_series;
pub use bollinger_pct_b::bollinger_pct_b_series;
pub use candlestick_patterns::{CandlestickPatternBar, candlestick_pattern_series};
pub use cci::cci_series;
pub use chaikin_oscillator::{chaikin_oscillator_from_candles, chaikin_oscillator_series};
pub use chandelier_exit::{ChandelierBar, chandelier_exit_series};
pub use cmf::cmf_series;
pub use cmo::cmo_series;
pub use dema::dema_series;
pub use donchian::donchian_series;
pub use elder_ray::elder_ray_series;
pub use ema::ema_series;
pub use force_index::force_index_series;
pub use hist_vol::hist_vol_log_returns_series;
pub use hull_ma::hull_ma_series;
pub use ichimoku::{IchimokuBar, ichimoku_series};
pub use kama::kama_series;
pub use keltner::keltner_series;
pub use kst::kst_series;
pub use kvo::kvo_series;
pub use linear_regression::linear_regression_slope_series;
pub use macd::macd_series;
pub use mama_fama::{MamaFamaBar, mama_fama_series};
pub use mass_index::mass_index_series;
pub use mcginley::mcginley_series;
pub use mfi::mfi_series;
pub use nvi_pvi::nvi_pvi_series;
pub use obv::obv_series;
pub use parabolic_sar::{ParabolicSarBar, parabolic_sar_series};
pub use pivot_classic::{PivotClassicBar, pivot_classic_series};
pub use pivot_fib::{PivotFibBar, pivot_fib_series};
pub use ppo::{PpoBar, ppo_series};
pub use pvo::{PvoBar, pvo_series};
pub use roc::roc_series;
pub use rolling_median::rolling_median;
pub use rsi::rsi_series;
pub use sma::sma_series;
pub use stoch_rsi::stochastic_rsi_series;
pub use stochastic::stochastic_series;
pub use supertrend::{SuperTrendBar, supertrend_series};
pub use tema::tema_series;
pub use trix::trix_series;
pub use tsi::tsi_series;
pub use ttm_squeeze::{TtmSqueezeBar, ttm_squeeze_series};
pub use ultosc::ultimate_oscillator_series;
pub use vidya::vidya_series;
pub use volume_ema::volume_ema_series;
pub use volume_profile::{VolumeProfileZones, volume_profile_zones};
pub use volume_sma::volume_sma_series;
pub use vortex::{VortexBar, vortex_series};
pub use vwap::{VwapBar, vwap_bands_series};
pub use vwma::vwma_series;
pub use williams_r::williams_r_series;
pub use wma::wma_series;
pub use zscore::zscore_series;
